# Generated by Django 4.1.4 on 2023-01-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='create_data',
        ),
    ]
