# Generated by Django 4.1.4 on 2023-01-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_create_time_post_create_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_data',
        ),
    ]
