# Generated by Django 4.1.4 on 2023-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_gander_about_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumary',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
