# Generated by Django 4.1.4 on 2023-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_sumary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumary',
            name='PhEmailone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sumary',
            name='city',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sumary',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
