# Generated by Django 4.1.4 on 2023-01-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_about_phemailone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='job',
            field=models.CharField(max_length=50),
        ),
    ]
