# Generated by Django 4.1.4 on 2023-01-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_skils_subtitle_skils_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skils',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='skils',
            name='title',
        ),
        migrations.AddField(
            model_name='skils',
            name='type',
            field=models.CharField(choices=[('Design', 'Design'), ('Coding', 'Coding')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
