# Generated by Django 4.1.4 on 2023-01-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_remove_skils_subtitle_remove_skils_title_skils_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skils',
            name='type',
            field=models.CharField(choices=[('skill1', 'skill1'), ('skill2', 'skill2')], max_length=10),
        ),
    ]
