# Generated by Django 4.1.4 on 2023-01-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_skils_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='title',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(default='', upload_to='about/'),
            preserve_default=False,
        ),
    ]
