# Generated by Django 4.1.4 on 2023-01-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_remove_testimonials_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='skils',
            name='type',
            field=models.CharField(choices=[('skill2', 'skill2'), ('skill1', 'skill1')], max_length=10),
        ),
    ]
