# Generated by Django 4.1.4 on 2023-01-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_alter_education_options_alter_professional_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skils',
            name='type',
            field=models.CharField(choices=[('skill1', 'skill1'), ('skill2', 'skill2')], max_length=10),
        ),
    ]
