# Generated by Django 4.1.4 on 2023-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_alter_skils_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skils',
            name='type',
            field=models.CharField(choices=[('skill2', 'skill2'), ('skill1', 'skill1')], max_length=10),
        ),
    ]
